# Generated by Django 2.1.7 on 2019-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0003_auto_20190226_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='food_pics'),
        ),
    ]
