# Generated by Django 2.1.7 on 2019-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0004_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
