# Generated by Django 2.1.1 on 2019-03-17 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefs_apprentice', '0005_recipe_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='download',
            field=models.ManyToManyField(blank=True, related_name='download', to=settings.AUTH_USER_MODEL),
        ),
    ]
