# Generated by Django 2.1.7 on 2019-03-15 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0005_recipe_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(blank=True, choices=[('liter', 'liter'), ('dl', 'dl'), ('kg', 'kg'), ('gram', 'gram'), ('ss', 'ss'), ('ts', 'ts'), ('klype', 'klype'), ('dråpe', 'dråpe'), ('boks', 'boks'), ('pakke', 'pakke'), ('pose', 'pose')], max_length=15)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chefs_apprentice.Ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='_recipe_ingredients_+', to='chefs_apprentice.ChosenIngredient'),
        ),
        migrations.AddField(
            model_name='choseningredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chefs_apprentice.Recipe'),
        ),
    ]
