# Generated by Django 2.1.7 on 2019-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0006_auto_20190319_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='niva',
            field=models.CharField(choices=[('E', 'Enkel'), ('I', 'Intermediat'), ('V', 'Vanskelig')], default='E', max_length=1),
        ),
    ]
