# Generated by Django 2.1.1 on 2019-03-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0006_auto_20190317_1344'),
        ('chefs_apprentice', '0006_auto_20190319_1012'),
    ]

    operations = [
    ]
