# Generated by Django 2.1.7 on 2019-03-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0007_recipe_niva'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tid',
            field=models.CharField(choices=[('L', 'Under 30 min'), ('M', 'Ca. 30-60 min'), ('S', 'Over 1 time')], default='L', max_length=1),
        ),
    ]
