# Generated by Django 2.1.7 on 2019-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs_apprentice', '0008_recipe_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='niva',
            field=models.CharField(choices=[('E', 'Enkel'), ('M', 'Middels'), ('V', 'Vanskelig')], default='E', max_length=1),
        ),
    ]
